# Generated by Django 4.2.4 on 2023-09-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('eventid', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.CharField(max_length=100)),
                ('eventdate', models.CharField(max_length=100)),
            ],
        ),
    ]
