# Generated by Django 4.2.4 on 2024-03-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_remove_course_id_course_courseid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='courseid',
        ),
        migrations.AddField(
            model_name='course',
            name='id',
            field=models.BigAutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
